name: Android Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' #JDK distro
          java-version: '17' #required Java version

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew #Gradle wrapper with perms.

      - name: Build with Gradle
        run: ./gradlew build
