name: Android Emulate

on:
  push:
    branches: [emulator]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 840
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx3g"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' #JDK distro
          java-version: '17' #required Java version

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew #Gradle wrapper with perms.

      - name: Assemble Debug #Build APKs only - faster than a full build
        run: ./gradlew assembleDebug

      - name: Start Emulator 
        #spins up an emulator on the github-hosted runner
        uses: reactivecircus/android-emulator-runner@v2 
        with: #explain all below
          api-level: 30 #our target-api 
          target: google_apis
          arch: x86_64
          profile: pixel_5 #device
          emulator-options: -no-snapshot -gpu swiftshader_indirect -noaudio -no-boot-anim
          script: ./gradlew connectedCheck
